name: Arduino CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sketch: ["blink-basic", "pwm-fade", "serial-telemetry", "button-alert"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Arduino CLI
        run: |
          wget https://downloads.arduino.cc/arduino-cli/arduino-cli_1.4.1_Linux_64bit.tar.gz
          tar -xzf arduino-cli_1.4.1_Linux_64bit.tar.gz
          chmod +x arduino-cli
          sudo mv arduino-cli /usr/local/bin/arduino-cli
          arduino-cli config init --additional-urls https://downloads.arduino.cc/packages/package_index.json
      - name: Install AVR core
        run: arduino-cli core install arduino:avr
      - name: Compile ${{ matrix.sketch }}
        run: arduino-cli compile --fqbn arduino:avr:uno ${{ matrix.sketch }}

  rust-tooling:
    runs-on: ubuntu-latest
    steps:
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev pkg-config
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo fmt
        working-directory: tools/rust-telemetry
        run: cargo fmt --all --check
      - name: cargo clippy
        working-directory: tools/rust-telemetry
        run: cargo clippy --all-targets --all-features -- -D warnings
